### PR TITLE
Dockerfile adding packages[ready to be merged]

### PR DESCRIPTION
**Pull request by wenyunie**
Hmisc is added for smoothly running the analysis.

### CODE REVIEW

**Comment by wenyunie** [comment]
also cleaned the output

**Review by monazhu — COMMENTED** [review]
@wenyunie for the Dockerfile change, I'm wondering whether the **upgrade = 'always'** argument should be included. The reason why I bring this up is because when package versions get updated, sometimes code can break (having experienced this first hand, I wish I knew more about package versions when my past self had to deal with it 🥲 )

**Comment by wenyunie** [comment]
> @wenyunie for the Dockerfile change, I'm wondering whether the **upgrade = 'always'** argument should be included. The reason why I bring this up is because when package versions get updated, sometimes code can break (having experienced this first hand, I wish I knew more about package versions when my past self had to deal with it 🥲 )

The purpose of this argument setting was to inhibit the prompt asking whether to upgrade (in a automatic workflow like container instantiation, this might mean the whole process could be just paused there, and there is nothing like a console where we can interactively choose). 

But indeed, 'always' might bring some packages to versions which we have no control of. Let me see first if 'never' could do

**Comment by wenyunie** [comment]
@monazhu  I think 'never' works better here, so that we know installing of this package with explicit version does not mix with other packages we do not have controls on version.

**Comment by wenyunie** [comment]
Actually in non-interactive sessions, 'ask' will be coerced to be 'always':
image

It is wonderful you noticed and mentioned this, otherwise we would go with implicit  or explicit 'always' anyway...

After some sorting out, I now strongly think 'never' would do the best. We now see that install hmisc with upgrade='never' is enough to run our code, and we know that the behavior of this line will always be the same even when some one tries to instantiate the docker image 10 years from now.  I don't know if it would be the same with 'always', maybe it will always chase the most recent packages:
image

**Comment by monazhu** [comment]
I'm glad we caught that one! Thanks for diving into the issue @wenyunie! 

Let me know when you're ready and I'll pull the merge through 😃

**Review by mishelly-h — APPROVED** [review]
PERFECT!

**Pull request merged**
